# Generated by Django 6.0.1 on 2026-04-14 21:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0002_session_sn_content_alter_assignment_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='due_date',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='session',
            new_name='session_ref',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='assignment',
            new_name='assignment_ref',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_url',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
