# Generated by Django 6.0.1 on 2026-04-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0003_rename_due_date_assignment_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assign_title',
            new_name='assignment_title',
        ),
    ]
