# Generated by Django 6.0.1 on 2026-04-16 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0005_alter_assignment_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='student',
            new_name='student_ref',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='file',
            new_name='submission_url',
        ),
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
