# Generated by Django 6.0.1 on 2026-04-16 16:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0006_rename_student_submission_student_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_url',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw'),
        ),
    ]
