# Generated by Django 6.0.1 on 2026-04-21 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0008_assignment_deleted_by_assignment_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_id',
        ),
    ]
