# Generated by Django 6.0.1 on 2026-04-22 03:14

from django.db import migrations

def copy_data_to_user(apps, schema_editor):
    Instructor = apps.get_model('lms_api', 'Instructor')
    Student = apps.get_model('lms_api', 'Student')
    
    for instructor in Instructor.objects.all():
        if instructor.user:
            instructor.user.first_name = instructor.first_name
            instructor.user.last_name = instructor.last_name
            instructor.user.email = instructor.email
            instructor.user.save()
            
    for student in Student.objects.all():
        if student.user:
            student.user.first_name = student.first_name
            student.user.last_name = student.last_name
            student.user.email = student.email
            student.user.save()

def reverse_copy_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0009_remove_user_card_id'),
    ]

    operations = [
        migrations.RunPython(copy_data_to_user, reverse_copy_data),
    ]
