# Generated by Django 6.0.1 on 2026-04-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0011_remove_instructor_email_remove_instructor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
